# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Check code coverage
      run: |
        coverage=$(grep -Po '(?<=<counter type="INSTRUCTION" missed="\d+" covered=")\d+(?=")' target/site/jacoco/jacoco.xml)
        total_missed=$(grep -Po '(?<=<counter type="INSTRUCTION" missed=")\d+(?=")' target/site/jacoco/jacoco.xml)
        total_covered=$(grep -Po '(?<=<counter type="INSTRUCTION" covered=")\d+(?=")' target/site/jacoco/jacoco.xml)
        total=$((total_missed + total_covered))
        coverage_percentage=$((total_covered * 100 / total))
        echo "Code coverage is $coverage_percentage%"
        if [ "$coverage_percentage" -lt 70 ]; then
          echo "Code coverage is below 70%"
          exit 1
        fi
